package adventofcode.aoc2023.day11

import adventofcode.AoCTest

class Day11Test extends AoCTest:
  override val lines: String =
    """...#......
      |.......#..
      |#.........
      |..........
      |......#...
      |.#........
      |.........#
      |..........
      |.......#..
      |#...#.....""".stripMargin
    
  val expanded = """....#........
                   |.........#...
                   |#............
                   |.............
                   |.............
                   |........#....
                   |.#...........
                   |............#
                   |.............
                   |.............
                   |.........#...
                   |#....#.......""".stripMargin.split('\n').toList

  test("part 1"):
    assertEquals(Day11(input).part1, 374)
  test("expand"):
    assertEquals(Universe.parse(input).expand.cells, Universe.parse(expanded).cells)

  test("part 2"):
    intercept[NotImplementedError]:
      assertEquals(Day11(input).part2, 0)
