package adventofcode.aoc2022.day23

import adventofcode.AoCTest
import adventofcode.aoc2022.day23.Field.*
import adventofcode.inputLines
import adventofcode.utils.coordinates.Coordinates

class Day23Test extends AoCTest {
  override val lines: String =
    """..............
      |..............
      |.......#......
      |.....###.#....
      |...#...#.#....
      |....#...##....
      |...#.###......
      |...##.#.##....
      |....#..#......
      |..............
      |..............
      |..............""".stripMargin
  test("is empty around") {
    val field = Field.parse(input)
    assertEquals(emptyAround(field.field, Coordinates(0, 6)), true)
  }
  test("part 1") {
    assertEquals(Day23(Field.parse(input)).part1, 110)
  }
  test("part 2") {
    assertEquals(Day23(Field.parse(input)).part2, 20)
  }
  test("next") {
    val initial = Field.parse(""".....
                                |..##.
                                |..#..
                                |.....
                                |..##.
                                |.....""".stripMargin.split('\n').toList)
    assertEquals(
      initial.show,
      """.....
        |..##.
        |..#..
        |.....
        |..##.
        |.....""".stripMargin
    )
    val next = initial.next
    assertEquals(
      next.show,
      """..##.
        |.....
        |..#..
        |...#.
        |..#..
        |.....""".stripMargin
    )
    assertEquals(
      next.next.show,
      """.....
        |..##.
        |.#...
        |....#
        |.....
        |..#..""".stripMargin
    )
    assertEquals(
      next.next.next.show,
      """..#..
        |....#
        |#....
        |....#
        |.....
        |..#..""".stripMargin
    )
    assertEquals(
      next.next.next.next.show,
      """..#..
        |....#
        |#....
        |....#
        |.....
        |..#..""".stripMargin
    )
  }
  test("next") {
    val field = Field.parse("""..............
                              |..............
                              |.......#......
                              |.....###.#....
                              |...#...#.#....
                              |....#...##....
                              |...#.###......
                              |...##.#.##....
                              |....#..#......
                              |..............
                              |..............
                              |..............""".stripMargin.split('\n').toList)
    assertEquals(
      field.next.show,
      """..............
        |.......#......
        |.....#...#....
        |...#..#.#.....
        |.......#..#...
        |....#.#.##....
        |..#..#.#......
        |..#.#.#.##....
        |..............
        |....#..#......
        |..............
        |..............""".stripMargin
    )
    assertEquals(
      field.next.next.show,
      """..............
        |.......#......
        |....#.....#...
        |...#..#.#.....
        |.......#...#..
        |...#..#.#.....
        |.#...#.#.#....
        |..............
        |..#.#.#.##....
        |....#..#......
        |..............
        |..............""".stripMargin
    )
    assertEquals(
      field.next.next.next.show,
      """..............
        |.......#......
        |.....#....#...
        |..#..#...#....
        |.......#...#..
        |...#..#.#.....
        |.#..#.....#...
        |.......##.....
        |..##.#....#...
        |...#..........
        |.......#......
        |..............""".stripMargin
    )
    assertEquals(
      field.next.next.next.next.show,
      """..............
        |.......#......
        |......#....#..
        |..#...##......
        |...#.....#.#..
        |.........#....
        |.#...###..#...
        |..#......#....
        |....##....#...
        |....#.........
        |.......#......
        |..............""".stripMargin
    )
    assertEquals(
      field.next.next.next.next.next.show,
      """.......#......
        |..............
        |..#..#.....#..
        |.........#....
        |......##...#..
        |.#.#.####.....
        |...........#..
        |....##..#.....
        |..#...........
        |..........#...
        |....#..#......
        |..............""".stripMargin
    )
  }
}
